# config/sidekiq.yml
:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 5 } %> # Adjust based on Render plan
:queues:
  - default
  - critical # Example of another queue
:timeout: 25 # Heroku/Render timeout is 30s, make Sidekiq timeout shorter